---
version: '3.7'
services:
  zookeeper1:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper1
    container_name: zookeeper1
    ports:
      - "2181:2181"
    command: zookeeper-server-start /etc/kafka/zookeeper.properties
    environment:
      EXTRA_ARGS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.18.0.jar=9103:/usr/share/jmx-exporter/zookeeper.yml
    volumes:
    - ./zookeeper1:/etc/kafka
    - ./jmx-exporter:/usr/share/jmx-exporter
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
  kafka1:
    image: confluentinc/cp-server:7.4.0
    hostname: kafka1
    container_name: kafka1
    depends_on:
      - zookeeper1
    command: kafka-server-start /etc/kafka/server.properties
    environment:
      EXTRA_ARGS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.18.0.jar=9101:/usr/share/jmx-exporter/kafka_broker.yml
    volumes:
    - ./kafka1:/etc/kafka
    - ./jmx-exporter:/usr/share/jmx-exporter
    - ./client:/home/appuser
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka1:19092", "--command-config", "client.properties", "--list"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 1536M

  kafka2:
    image: confluentinc/cp-server:7.4.0
    hostname: kafka2
    container_name: kafka2
    depends_on:
      - zookeeper1
    command: kafka-server-start /etc/kafka/server.properties
    environment:
      EXTRA_ARGS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.18.0.jar=9102:/usr/share/jmx-exporter/kafka_broker.yml
    volumes:
    - ./kafka2:/etc/kafka
    - ./jmx-exporter:/usr/share/jmx-exporter
    - ./client:/home/appuser
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka1:19092", "--command-config", "client.properties", "--list"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 1536M
  
  kafka3:
    image: confluentinc/cp-server:7.4.0
    hostname: kafka3
    container_name: kafka3
    depends_on:
      - zookeeper1
    command: kafka-server-start /etc/kafka/server.properties
    environment:
      EXTRA_ARGS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.18.0.jar=9103:/usr/share/jmx-exporter/kafka_broker.yml
    volumes:
    - ./kafka3:/etc/kafka
    - ./jmx-exporter:/usr/share/jmx-exporter
    - ./client:/home/appuser
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka1:19092", "--command-config", "client.properties", "--list"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 1536M

  schema-registry:
    image: confluentinc/cp-schema-registry:7.4.0
    hostname: schema-registry
    container_name: schema-registry
    command: schema-registry-start /etc/schema-registry/schema-registry.properties
    ports:
      - "8081:8081"
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    volumes:
    - ./schema-registry:/etc/schema-registry
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M

  connect:
    image: localbuild/connect:v1
    hostname: connect
    container_name: connect
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - schema-registry
    command: connect-distributed /etc/kafka/connect-distributed.properties
    ports:
      - "8083:8083"
    volumes:
    - ./connect:/etc/kafka
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2048M

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.4.0
    hostname: control-center
    container_name: control-center
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - schema-registry
      - connect
    ports:
      - "9021:9021"
    command: control-center-start /etc/confluent-control-center/control-center-production.properties
    environment:
      PORT: 9021
    volumes:
    - ./confluent-control-center:/etc/confluent-control-center
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M

  # kfkclient:
  #   build: ./client
  #   hostname: kfkclient
  #   container_name: kfkclient
  #   depends_on:
  #     - kafka1
  #   volumes:
  #   - ./client:/opt/client
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.1"
  #         memory: 256M

  openldap:
    image: osixia/openldap:1.3.0
    hostname: openldap
    container_name: openldap
    environment:
        LDAP_ORGANISATION: "ConfluentDemo"
        LDAP_DOMAIN: "confluentdemo.io"
        LDAP_BASE_DN: "dc=confluentdemo,dc=io"
    ports:
      - "389:389"
    volumes:
        - ./ldap/ldap_users:/container/service/slapd/assets/config/bootstrap/ldif/custom
    command: "--copy-service --loglevel debug"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 256M


